### ISSUE TITLE
possible typo, wishes

### ISSUE THREAD

**Issue by simonmichael** [vmchale/command-line-tweeter#2]
Loving this! Thanks! Some wishes: 
tweet --version
tweet show TWEETID
tweet COMMAND --open  # view corresponding part of web ui if any

Informative readme. "Reasons not to use tweet-hs: You want to extend your tools in haskell" - is that a typo ?

**Comment by vmchale** [comment]
Ah yes, you're right! I evidently copied the wrong lines from the Rust repo.

Thanks!
